// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SorteadorSinal2.repositorios;

namespace SorteadorSinal2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230316211055__init")]
    partial class _init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SorteadorSinal2.models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Estado")
                        .HasColumnType("varchar(2) CHARACTER SET utf8mb4")
                        .HasMaxLength(2);

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Rio preto",
                            Cpf = "222.222.222-22",
                            Estado = "Sp",
                            Nascimento = new DateTime(1999, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maricota da Silva",
                            Telefone = "11 99222221"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Rio preto",
                            Cpf = "222.222.222-22",
                            Estado = "Sp",
                            Nascimento = new DateTime(1990, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Jose pereira",
                            Telefone = "11 99222222"
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "Rio preto",
                            Cpf = "222.222.222-22",
                            Estado = "Sp",
                            Nascimento = new DateTime(2018, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Joao Costa",
                            Telefone = "11 99222223"
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Rio preto",
                            Cpf = "222.222.222-22",
                            Estado = "Sp",
                            Nascimento = new DateTime(1949, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Larisa casablanca",
                            Telefone = "11 99222224"
                        },
                        new
                        {
                            Id = 5,
                            Cidade = "Rio preto",
                            Cpf = "222.222.222-22",
                            Estado = "Sp",
                            Nascimento = new DateTime(2000, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Joana camargo",
                            Telefone = "11 99222225"
                        });
                });

            modelBuilder.Entity("SorteadorSinal2.models.Participantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClientesId")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdPromocao")
                        .HasColumnType("int");

                    b.Property<int?>("PromocoesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientesId");

                    b.HasIndex("PromocoesId");

                    b.ToTable("Participantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdCliente = 2,
                            IdPromocao = 2
                        },
                        new
                        {
                            Id = 2,
                            IdCliente = 4,
                            IdPromocao = 2
                        },
                        new
                        {
                            Id = 3,
                            IdCliente = 2,
                            IdPromocao = 1
                        },
                        new
                        {
                            Id = 4,
                            IdCliente = 1,
                            IdPromocao = 2
                        },
                        new
                        {
                            Id = 5,
                            IdCliente = 5,
                            IdPromocao = 1
                        },
                        new
                        {
                            Id = 6,
                            IdCliente = 4,
                            IdPromocao = 3
                        },
                        new
                        {
                            Id = 7,
                            IdCliente = 1,
                            IdPromocao = 3
                        });
                });

            modelBuilder.Entity("SorteadorSinal2.models.Promocoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("VigenciaFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("VigenciaInicio")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Promocoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Churrascaria boi feliz",
                            VigenciaFim = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VigenciaInicio = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Funeraria cliente agradecido",
                            VigenciaFim = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VigenciaInicio = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Fabrica de gelos escorrega",
                            VigenciaFim = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VigenciaInicio = new DateTime(2023, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SorteadorSinal2.models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "naira",
                            Nome = "Naira Danile",
                            Senha = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Login = "josi",
                            Nome = "Josiane bueno",
                            Senha = "654321"
                        });
                });

            modelBuilder.Entity("SorteadorSinal2.models.Vencedores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClientesId")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdPromocao")
                        .HasColumnType("int");

                    b.Property<int?>("PromocoesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientesId");

                    b.HasIndex("PromocoesId");

                    b.ToTable("Vencedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdCliente = 2,
                            IdPromocao = 2
                        },
                        new
                        {
                            Id = 2,
                            IdCliente = 4,
                            IdPromocao = 2
                        },
                        new
                        {
                            Id = 3,
                            IdCliente = 4,
                            IdPromocao = 3
                        });
                });

            modelBuilder.Entity("SorteadorSinal2.models.Participantes", b =>
                {
                    b.HasOne("SorteadorSinal2.models.Clientes", "Clientes")
                        .WithMany()
                        .HasForeignKey("ClientesId");

                    b.HasOne("SorteadorSinal2.models.Promocoes", "Promocoes")
                        .WithMany()
                        .HasForeignKey("PromocoesId");
                });

            modelBuilder.Entity("SorteadorSinal2.models.Vencedores", b =>
                {
                    b.HasOne("SorteadorSinal2.models.Clientes", "Clientes")
                        .WithMany()
                        .HasForeignKey("ClientesId");

                    b.HasOne("SorteadorSinal2.models.Promocoes", "Promocoes")
                        .WithMany()
                        .HasForeignKey("PromocoesId");
                });
#pragma warning restore 612, 618
        }
    }
}
